server:
  #  compression:
  #    enabled: true
  #    min-response-size: 2KB
  #    mime-types: "application/json"
  port: 20002
  servlet:
    context-path: /
spring:
  application:
    name: easyexcel-demo
  datasource:
    url: jdbc:mysql://localhost:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xx
    password: xx
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 20000
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: ${redis_host:localhost}
    port: ${redis_port:6379}
    password: ${redis_password:}
    database: 1
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
      shutdown-timeout: 10000ms
    timeout: 60000ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.h7culture.manage: debug

